// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/csrf.proto

package csrf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CSRFService_GenerateToken_FullMethodName = "/csrf.CSRFService/GenerateToken"
	CSRFService_ValidateToken_FullMethodName = "/csrf.CSRFService/ValidateToken"
)

// CSRFServiceClient is the client API for CSRFService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CSRFServiceClient interface {
	GenerateToken(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GenerateTokenResponse, error)
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
}

type cSRFServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCSRFServiceClient(cc grpc.ClientConnInterface) CSRFServiceClient {
	return &cSRFServiceClient{cc}
}

func (c *cSRFServiceClient) GenerateToken(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GenerateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTokenResponse)
	err := c.cc.Invoke(ctx, CSRFService_GenerateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cSRFServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, CSRFService_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CSRFServiceServer is the server API for CSRFService service.
// All implementations must embed UnimplementedCSRFServiceServer
// for forward compatibility.
type CSRFServiceServer interface {
	GenerateToken(context.Context, *Empty) (*GenerateTokenResponse, error)
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	mustEmbedUnimplementedCSRFServiceServer()
}

// UnimplementedCSRFServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCSRFServiceServer struct{}

func (UnimplementedCSRFServiceServer) GenerateToken(context.Context, *Empty) (*GenerateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateToken not implemented")
}
func (UnimplementedCSRFServiceServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedCSRFServiceServer) mustEmbedUnimplementedCSRFServiceServer() {}
func (UnimplementedCSRFServiceServer) testEmbeddedByValue()                     {}

// UnsafeCSRFServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CSRFServiceServer will
// result in compilation errors.
type UnsafeCSRFServiceServer interface {
	mustEmbedUnimplementedCSRFServiceServer()
}

func RegisterCSRFServiceServer(s grpc.ServiceRegistrar, srv CSRFServiceServer) {
	// If the following call pancis, it indicates UnimplementedCSRFServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CSRFService_ServiceDesc, srv)
}

func _CSRFService_GenerateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CSRFServiceServer).GenerateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CSRFService_GenerateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CSRFServiceServer).GenerateToken(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CSRFService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CSRFServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CSRFService_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CSRFServiceServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CSRFService_ServiceDesc is the grpc.ServiceDesc for CSRFService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CSRFService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "csrf.CSRFService",
	HandlerType: (*CSRFServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateToken",
			Handler:    _CSRFService_GenerateToken_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _CSRFService_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/csrf.proto",
}
